#! /usr/bin/env python
from Bio import SeqIO
import os
import sys
file_list = [f for f in os.listdir(sys.argv[1]) if f.endswith(".fna")]
final = open(sys.argv[2],"a+")
for seq in file_list:
        name = seq.rsplit(".",1)[0]
	for record in SeqIO.parse(seq,"fasta"):
		final.write(">"+name+"_"+str(record.id)+"\n")
                final.write(str(record.seq)+"\n")
final.close()
